name: Ping Render Servers

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes (UTC)

  workflow_dispatch: # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render API (bot-1-nyuj)
        run: curl -I https://bot-1-nyuj.onrender.com

      - name: Ping Render API (bot-ir83)
        run: curl -I https://bot-ir83.onrender.com/api/settings
